change_pins: false
change_transport: false
change_node: false

transport:
  use_wifi: true
  agent_ip: 10.0.0.36
  agent_port: 8888
  wifi_ssid: ssid_name
  wifi_password: password

pins:
  - number: 1
    mode: analog_input

  - number: 2
    mode: digital_output

node:
  node_name: esp32
  service_name: set_config
  publisher_name: read_pins
  subcriber_name: write_pins
