target_topic: /esp32_set_config
read_only: false
pins:
  - number: 26
    mode: digital_input

  - number: 14
    mode: digital_output

  - number: 33
    mode: analog_input

  - number: 25
    mode: analog_output

